### ISSUE TITLE
Unable to run train.py with basic settings.

### ISSUE THREAD

**Issue by chouhanyang** [kvablack/susie#2]
Hello, I'm trying to run train.py, but got error on ```instruct-pix2pix``` model. Not sure which one it is on huggingfase.

```
Repository Not Found for url: https://huggingface.co/instruct-pix2pix/resolve/main/unet/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chouyang/susie/susie/scripts/train.py", line 633, in <module>
    app.run(main)
  File "/home/chouyang/susie/env/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/chouyang/susie/env/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/chouyang/susie/susie/scripts/train.py", line 279, in main
    pretrained_model_def, pretrained_params = load_pretrained_unet(
  File "/home/chouyang/susie/susie/susie/model.py", line 146, in load_pretrained_unet
    model_def, params = FlaxUNet2DConditionModel.from_pretrained(
  File "/home/chouyang/susie/env/lib/python3.10/site-packages/diffusers/models/modeling_flax_utils.py", line 307, in from_pretrained
    model, model_kwargs = cls.from_config(
  File "/home/chouyang/susie/env/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 218, in from_config
    config, kwargs = cls.load_config(pretrained_model_name_or_path=config, return_unused_kwargs=True, **kwargs)
  File "/home/chouyang/susie/env/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 362, in load_config
    raise EnvironmentError(
OSError: instruct-pix2pix is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login`.
wandb: Waiting for W&B process to finish... (failed 1).
```

Any pointers? Thank you.

**Comment by kvablack** [comment]
This is my bad, I was loading the InstructPix2Pix weights from a local directory since I had to convert them to Flax manually. It should be fixed now!

**Comment by chouhanyang** [comment]
Thank you for the quick fix @kvablack, really appreciate it.
