### ISSUE TITLE
error when evaluating

### ISSUE THREAD

**Issue by abdotaarek** [kvablack/susie#3]
hello, when i try to evaluate i get this error, what could be possibly missing

(susie-calvin) abdo@abdo:~/calvin-sim$ ./eval_susie.sh
Traceback (most recent call last):
  File "calvin_models/calvin_agent/evaluation/evaluate_policy_subgoal_diffusion.py", line 12, in <module>
    import jax_diffusion_model
  File "/home/abdo/calvin-sim/calvin_models/calvin_agent/evaluation/jax_diffusion_model.py", line 1, in <module>
    from susie.model import create_sample_fn
ModuleNotFoundError: No module named 'susie'

**Comment by pranavatreya** [comment]
Hey, did you make sure to download and pip install the SuSIE code base (this repo)?

**Comment by abdotaarek** [comment]
Yes i did , but should i install it in the calvin-sim folder?

**Comment by pranavatreya** [comment]
No you can install it anywhere
